Reglas ruff
pchesini/vetsoft pull request #11
Opened 2024-06-03 10:53 UTC by pchesini

[Se Agregó regla ruff COM812 para comas faltantes

2024-06-03 13:39 UTC, ManuelScianca approved these changes

2024-06-03 13:43 UTC, franlucich requested changes

2024-06-03 13:43 UTC, franlucich commented on app/ruff.toml
> +[lint]
Fíjate que creaste otro archivo ruff en app/, es mejor si agregas la regla en el que ya estaba en el root del repo

2024-06-03 23:02 UTC, franlucich approved these changes

2024-06-05 17:54 UTC, fdasilva5 approved these changes

2024-06-05 18:17 UTC, merged