Validacion del campo name
pchesini/vetsoft pull request #12
Opened 2024-06-04 22:25 UTC by pchesini

Se agrego validacion solo para permitir letras y espacios

2024-06-06 01:00 UTC, franlucich requested changes

2024-06-06 01:00 UTC, franlucich commented on functional_tests/tests.py
> -
Me eliminaste el test

2024-06-06 01:00 UTC, franlucich commented on functional_tests/tests.py
>  import os
En todo el archivo eliminaste los comentarios de documentacion

2024-06-06 01:57 UTC, franlucich approved these changes, later dismissed

2024-06-06 02:09 UTC, ManuelScianca approved these changes

2024-06-08 22:23 UTC, franlucich requested changes

2024-06-08 22:23 UTC, franlucich commented on functional_tests/tests.py
> -
eliminaste este test

2024-06-08 23:42 UTC, franlucich approved these changes

2024-06-08 23:42 UTC, merged