Validación de numero de teléfono
pchesini/vetsoft pull request #18
Opened 2024-07-01 23:40 UTC by fdasilva5

En este PR se realizaron las siguientes modificaciones:

- Se modifico el test para validar que se muestra un error si el numero de teléfono ingresado comienza con '54'. Anteriormente, el test solo verificaba que el numero que escribimos manualmente comience con '54', de lo contrario mostrar un error.
- Agregamos una validación que asegure que el numero de teléfono ingresado sea solo numérico
- Agrego test de unidad para validar que el telefoneo sea numérico y, de no ser así, mostrar un error
- Agrego test e2e para validar que el teléfono sea numérico, en caso contrario, mostrar un error

2024-07-02 00:48 UTC, ManuelScianca approved these changes

2024-07-02 02:20 UTC, franlucich requested changes

2024-07-02 02:20 UTC, franlucich commented on functional_tests/tests.py
> +
quedó el test vacio acá, me parece que le erraste en el ultimo merge.  Más adelante quedó el test viejo

2024-07-04 13:27 UTC, fdasilva5 commented on functional_tests/tests.py
> +
Corregido.

2024-07-05 12:54 UTC, franlucich approved these changes

2024-07-06 13:02 UTC, pchesini approved these changes

2024-07-06 13:08 UTC, merged